version: '3.3'
services:
  db:
    build: ./pgsample
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: pwd
    
  adminer:
    image: adminer
    ports:
      - 127.0.0.1:8080:8080

volumes:
  db: